micronaut:
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
    application:
        name: oncostore
datasources:
    default:
      #url: jdbc:mariadb://${db-host}/${db-name}?maxPoolSize=150&pool&log=true&rewriteBatchedStatements=true
      url: jdbc:mariadb://${db-host}/${db-name}
      username: ${db-user}
      password: ${db-pwd}
      driverClassName: org.mariadb.jdbc.Driver
endpoints:
    health:
        enabled: true
        sensitive: false
        details-visible: ANONYMOUS