micronaut:
    application:
      name: oncostore
    server:
      port: ${variantstore-port}
    router:
      static-resources:
          swagger:
              paths:
                - classpath:META-INF/swagger
              mapping: /swagger/**
    security:
      enabled: true
      oauth2:
        enabled: true
        clients:
          keycloak:
            client-secret: <<my client id>>
            client-id: <<my client secret>>
            openid:
              issuer: <<my openid issuer>>
datasources:
    default:
      url: jdbc:mariadb://${db-host}/${db-name}?maxPoolSize=150&pool&log=true&rewriteBatchedStatements=true
      username: ${db-user}
      password: ${db-pwd}
      driverClassName: org.mariadb.jdbc.Driver
endpoints:
    health:
      enabled: true
      sensitive: false
      details-visible: ANONYMOUS
    routes:
      enabled: true
      sensitive: false