micronaut:
    application:
        name: variantstore
contact:
    first-name: Hello
    last-name: Word
    email: hellow.word@example.com
database:
    schema-uri: "src/test/resources/oncostore-model.sql"
datasources:
        default:
            url: jdbc:h2:${h2-path}/variantstore;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
            username: testuser
            password: ""
            driverClassName: org.h2.Driver